apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  project: default

  source:
    repoURL: "https://github.com/JunedConnect/project-bravo-terragrunt.git"
    targetRevision: main # this is the branch that argocd will be using as the source of truth
    path: argocd/apps

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: myapp-ns
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true