---

# deployment create

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: 677276074604.dkr.ecr.eu-west-2.amazonaws.com/weather-app
        ports:
        - containerPort: 8080

---

# clusterIP create

apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
spec:
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP

---

# ingress create

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    cert-manager.io/cluster-issuer: "issuer"
spec:
  ingressClassName: nginx # this has to be the same ingressClassName as your ingresscontroller
  rules:
  - host: app.lab.juned.co.uk
    http:
      paths:
       - path: /
         pathType: Prefix
         backend:
          service:
            name: myapp-svc
            port:
              number: 80
  tls:
  - hosts:
    - app.lab.juned.co.uk
    secretName: app-ingress-tls