name: terragrunt destroy

on:
  workflow_dispatch:

# on:
#     push:
#         branches:
#             - dev


jobs:
    terragruntdestroy:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: "./terraform/"
        environment: aws
    
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to AWS
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

            # - name: Set up Terraform
            #   uses: hashicorp/setup-terraform@v3
            #   with:
            #     terraform_version: 1.11.1

            # - name: Terraform Init
            #   run: terraform init
              
            # - name: Terraform Destroy
            #   run: terraform destroy -auto-approve

            - name: install terragrunt
              uses: gruntwork-io/terragrunt-action@v3
              with:
                tg_version: '0.83.0'
                # tofu_version: '1.10.1'
              
            - name: terragrunt init
              run: |
                cd environments/dev/
                terragrunt init -all

            - name: terragrunt destroy
              run: |
                cd environments/dev/
                terragrunt destroy -all