name: terragrunt apply

on:
  workflow_dispatch:

# on:
#     push:
#         branches:
#             - dev


jobs:
    terragruntapply:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: "./terraform/"
        environment: aws
    
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to AWS
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

            # - name: Set up Terraform
            #   uses: hashicorp/setup-terraform@v3
            #   with:
            #     terraform_version: 1.11.1

            # - name: Terraform Init
            #   run: terraform init

            # - name: Terraform Apply
            #   run: terraform apply -auto-approve

            - name: install terragrunt
              uses: gruntwork-io/terragrunt-action@v3
              with:
                tg_version: '0.83.0'
                # tofu_version: '1.10.1'
              
            - name: terragrunt init
              run: |
                cd environments/dev/
                terragrunt init -all

            - name: terragrunt apply
              run: |
                cd environments/dev/
                terragrunt apply -all

            - name: Update kubeconfig for EKS cluster
              run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

            - name: Deploy Cert-Manager issuer.yaml
              run: kubectl apply -f ../cert-man/issuer.yml

            - name: Deploy ArgoCD App Deployment apps-argocd.yaml
              run: kubectl apply -f ../argocd/argocd-git.yml