name: Docker Build & Deploy

on:
  workflow_dispatch:

# on:
#     push:
#         branches:
#             - dev


jobs:
    Docker:
        runs-on: ubuntu-24.04
        defaults:
            run:
                working-directory: "./app/"
        env:
          ECR_AWS_REGION: "eu-west-2"
          AWS_REGISTRY: "677276074604.dkr.ecr.eu-west-2.amazonaws.com"
        permissions:
            security-events: write # for github/codeql-action/upload-sarif to upload SARIF results

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to AWS
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.ECR_AWS_REGION }}
            - name: Login to AWS ECR
              uses: docker/login-action@v3
              with:
                registry: ${{ env.AWS_REGISTRY }}
                username: ${{ secrets.AWS_ACCESS_KEY }}
                password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            - name: Build
              run: |
                docker build -t weather-app .
                docker tag weather-app:latest ${{ env.AWS_REGISTRY }}/weather-app:latest

            - name: Trivy Scan
              uses: aquasecurity/trivy-action@master
              with:
                image-ref: weather-app:latest
                severity: 'CRITICAL,HIGH'
                format: 'sarif'
                output: 'trivy-results-Docker.sarif'
                exit-code: 0   # 1 means that any vulnerabilities found, that meet the severity criteria, will raise an error and will not allow the pipeline code to continue. 0 would allow the pipeline code to continue no matter the vulnerability.
      
            - name: Upload Trivy scan results to GitHub Security tab
              uses: github/codeql-action/upload-sarif@v3
              with:
                sarif_file: 'trivy-results-Docker.sarif'
                wait-for-processing: true

            - name: Push to ECR
              run: |
                docker push ${{ env.AWS_REGISTRY }}/weather-app:latest