name: Terragrunt Destroy

on:
  workflow_dispatch:

# on:
#     push:
#         branches:
#             - dev


jobs:
    TerragruntDestroy:
        runs-on: ubuntu-24.04
        defaults:
            run:
                working-directory: "./terraform/"
        env:
          AWS_REGION: "eu-west-2"
          ENVIRONMENT: "prod"
    
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to AWS
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

            - name: Install Terragrunt
              uses: gruntwork-io/terragrunt-action@v3
              with:
                tg_version: '0.83.0'
                tofu_version: '1.10.1'
              
            - name: Terragrunt Init
              run: |
                cd environments/${{ env.ENVIRONMENT }}/
                terragrunt init -all -upgrade

            - name: Terragrunt Destroy
              run: |
                cd environments/${{ env.ENVIRONMENT }}/
                terragrunt destroy -all --non-interactive