name: Terragrunt Apply

on:
  workflow_dispatch:
        inputs:
            cicdenvironment:
                description: 'Choose environment'
                required: true
                type: choice
                options:
                    - dev
                    - prod


jobs:
  Terragrunt-Apply-Dev:
    if: ${{ github.event.inputs.cicdenvironment == 'dev' }}
    uses: junedconnect/project-bravo-terragrunt/.github/workflows/Terragrunt-Reusable-Workflows.yml@main
    with:
      aws-region: "eu-west-1"
      environment: "dev"
      eks-cluster-name: "juned-cluster"
      action: "apply"
    secrets:
      aws-access-key: ${{ secrets.AWS_ACCESS_KEY }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  Terragrunt-Apply-Prod:
    if: ${{ github.event.inputs.cicdenvironment == 'prod' }}
    uses: junedconnect/project-bravo-terragrunt/.github/workflows/Terragrunt-Reusable-Workflows.yml@main
    with:
      aws-region: "eu-west-2"
      environment: "prod"
      eks-cluster-name: "juned-cluster"
      action: "apply"
    secrets:
      aws-access-key: ${{ secrets.AWS_ACCESS_KEY }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}